# tf_demo_table_02
# 

resource "snowflake_table" "tf_demo_table_02" {
    database        = var.db_name
    schema          = var.schema_name
    name            = "TF_DEMO_TABLE_02"
    cluster_by      = ["cast(substr(KAL_WO_OTW_ID, 1, 4 )|| substr(KAL_WO_OTW_ID, 7, 2) as int)"]
    comment = "Example for table generated by terraform. HMS analytical software GmbH 28.03.2025"
    data_retention_time_in_days = 1
    column {
        name            = "KAL_WO_OTW_ID"
        type            = "VARCHAR(8)"
        comment         = "ID f Kalenderwoche ohne Teilwoche"
        nullable        = false
    }
    column {
        name            = "MA_ID"
        type            = "NUMBER(38, 0)"
        comment         = "Markt-ID, DWH-generierte ID"
        nullable        = false
    }
    column {
        name            = "NAN_ART_ID"
        type            = "NUMBER(38, 0)"
        comment         = "ID f Nationale Artikelnummer, DWH-generierte ID"
        nullable        = false
    }
    column {
        name            = "LAGER_NR"
        type            = "NUMBER(38, 0)"
        comment         = "Lager Nummer aus EDW.F_ZAM_BESTAND_MA"
        nullable        = false
    }
    column {
        name            = "FEHLMG"
        type            = "NUMBER(38, 0)"
        comment         = "Fehlmenge aus WVS, letzte 2 Wochen"
        nullable        = true
    }
}
