# tf_demo_table_01
# 

resource "snowflake_table" "tf_demo_table_01" {
    database        = var.db_name
    schema          = var.schema_name
    name            = "TF_DEMO_TABLE_01"
	comment = "Example for table generated by terraform. HMS analytical software GmbH 28.03.2025"
    data_retention_time_in_days = 1
    column {
        name            = "KAL_TAG_ID"
        type            = "DATE"
        comment         = "ID f Kalendertag"
        nullable        = false
    }
    column {
        name            = "MA_ID"
        type            = "NUMBER(38, 0)"
        comment         = "Markt-ID, DWH-generierte ID"
        nullable        = false
    }
    column {
        name            = "NAN_ART_ID"
        type            = "NUMBER(38, 0)"
        comment         = "ID f Nationale Artikelnummer, DWH-generierte ID"
        nullable        = false
    }
    column {
        name            = "AKTIONSKATEGORIE"
        type            = "VARCHAR(100)"
        default         {constant = " "}
        nullable        = false
    }
    column {
        name            = "ABBILDUNG"
        type            = "VARCHAR(40)"
        default         {constant = " "}
        nullable        = false
    }
}
